Advantages of using numpy over python lists/dicts/sets:
- contiguous allocation in memory
- vectorized operation - you can apply an operation to all the elements of the array without usign loops

from stackoverflow:
- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object.
- A NumPy array is an array of uniform values

In [1]:
import numpy as np

In [52]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [53]:
s = (5,5)
a = np.zeros(s)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
a.dtype

dtype('float64')

In [55]:
a.ndim, a.shape, a.size

(2, (5, 5), 25)

In [56]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [57]:
zeros_2d = np.zeros((3,3))
zeros_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
zeros = np.zeros((5,), dtype=int) #can use np.float, float, d etc.
zeros

array([0, 0, 0, 0, 0])

In [59]:
#two dimensional array
# shape gives (row, column) size
b = np.array([[1,2,3],[4,5,6]],dtype=np.float64)
b, b.size, b.ndim, b.shape, b.dtype

(array([[1., 2., 3.],
        [4., 5., 6.]]), 6, 2, (2, 3), dtype('float64'))

In [60]:
# dangerous, sets random values
empty_arr = np.empty(5, dtype=int)
empty_arr

array([ 25363580, 242286593,  23330903, 880281213,  41682292])

In [65]:
# linespace gives values with a fixed width
# give me 10 values between 0 to 20 with fixed width
a = np.linspace(0,20,10) 
a

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [74]:
# arange, similar to python's range
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [75]:
# but you can add a width here
np.arange(0,5,2)

array([0, 2, 4])

In [79]:
np.random.standard_normal(2)

array([-0.58509257, -1.04953123])

In [78]:
np.random.standard_normal((2,3))

array([[ 0.42637808, -2.10293507, -0.36780956],
       [-2.0175763 ,  1.25212513,  0.90645691]])

In [89]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))
a, b

(array([[ 2.42137651,  0.10780348, -0.86041016],
        [-0.1132876 ,  1.69322429, -0.8910119 ]]),
 array([[ 1.04029691, -0.97708113, -0.934894  ],
        [ 1.17730708, -0.00489127,  0.75824616]]))

In [91]:
#stacks in a sequence, row wise
np.vstack((a,b))

array([[ 2.42137651,  0.10780348, -0.86041016],
       [-0.1132876 ,  1.69322429, -0.8910119 ],
       [ 1.04029691, -0.97708113, -0.934894  ],
       [ 1.17730708, -0.00489127,  0.75824616]])

In [90]:
# stacks in a sequence column wise
np.hstack((a,b))

array([[ 2.42137651,  0.10780348, -0.86041016,  1.04029691, -0.97708113,
        -0.934894  ],
       [-0.1132876 ,  1.69322429, -0.8910119 ,  1.17730708, -0.00489127,
         0.75824616]])

In [92]:
a.transpose()

array([[ 2.42137651, -0.1132876 ],
       [ 0.10780348,  1.69322429],
       [-0.86041016, -0.8910119 ]])

In [94]:
np.save('example.npy',np.vstack((a,b)))

In [95]:
np.load('example.npy')

array([[ 2.42137651,  0.10780348, -0.86041016],
       [-0.1132876 ,  1.69322429, -0.8910119 ],
       [ 1.04029691, -0.97708113, -0.934894  ],
       [ 1.17730708, -0.00489127,  0.75824616]])