## creating numpy arrays with mixed types
- hybrid of list and dict. 
- list to access rows. 
- dict to access columns. 
- specify rows using numpy tuples. 

In [2]:
import numpy as np

In [9]:
person_data_ref = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age','i8')]
person_data_ref

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [10]:
people = np.zeros((4), dtype=person_data_ref)
people

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [13]:
people['name'], people['height'], people['weight'], people['age']

(array([b'', b'', b'', b''], dtype='|S6'),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0, 0, 0, 0], dtype=int64))

In [17]:
people[0] = ('alpha', 160, 150, 20)
people[3] = ('delta', 170, 200, 23)

In [18]:
people[0]

(b'alpha', 160., 150., 20)

In [22]:
people[0:] # or just print people

array([(b'alpha', 160., 150., 20), (b'',   0.,   0.,  0),
       (b'',   0.,   0.,  0), (b'delta', 170., 200., 23)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [24]:
ages = people['age']
ages

array([20,  0,  0, 23], dtype=int64)

In [31]:
people['name']

array([b'alpha', b'', b'', b'delta'], dtype='|S6')

In [41]:
ages/2 #does not change people['age']

array([10. ,  0. ,  0. , 11.5])

In [42]:
people[['name','age']] # prints only name and age

array([(b'alpha', 20), (b'',  0), (b'',  0), (b'delta', 23)],
      dtype={'names':['name','age'], 'formats':['S6','<i8'], 'offsets':[0,22], 'itemsize':30})

In [34]:
#multi dimensional
many_people = np.zeros((4,3,2), dtype=person_data_ref)
many_people

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [35]:
many_people[3,2,1] = ('corey',173,180,30)
many_people

array([[[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'corey', 173., 180., 30)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [36]:
many_people['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0., 173.]]])

In [44]:
many_people[['height', 'weight']]

array([[[(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)]],

       [[(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)]],

       [[(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)]],

       [[(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (  0.,   0.)],
        [(  0.,   0.), (173., 180.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

## Record arrays

In [49]:
person_record = np.rec.array([('alpha', 160, 150, 20),('delta', 170, 200, 23)], dtype=person_data_ref)
person_record

rec.array([(b'alpha', 160., 150., 20), (b'delta', 170., 200., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [52]:
person_record[0].age #index instead of attribute

20